#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v19
# autospec commit: f35655a
#
Name     : qatlib
Version  : 24.09.0
Release  : 10
URL      : https://github.com/intel/qatlib/archive/24.09.0/qatlib-24.09.0.tar.gz
Source0  : https://github.com/intel/qatlib/archive/24.09.0/qatlib-24.09.0.tar.gz
Summary  : Provides access to Intel QAT hardware accelerated cryptography and compression
Group    : Development/Tools
License  : BSD-3-Clause
Requires: qatlib-bin = %{version}-%{release}
Requires: qatlib-lib = %{version}-%{release}
Requires: qatlib-license = %{version}-%{release}
Requires: qatlib-man = %{version}-%{release}
Requires: qatlib-services = %{version}-%{release}
BuildRequires : file
BuildRequires : nasm-bin
BuildRequires : numactl-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
![Linux build with gcc](https://github.com/intel/qatlib/actions/workflows/linux_build_gcc.yml/badge.svg)
![CodeQL scan](https://github.com/intel/qatlib/actions/workflows/codeql.yml/badge.svg)
[![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/intel/qatlib/badge)](https://api.securityscorecards.dev/projects/github.com/intel/qatlib)

%package bin
Summary: bin components for the qatlib package.
Group: Binaries
Requires: qatlib-license = %{version}-%{release}
Requires: qatlib-services = %{version}-%{release}

%description bin
bin components for the qatlib package.


%package dev
Summary: dev components for the qatlib package.
Group: Development
Requires: qatlib-lib = %{version}-%{release}
Requires: qatlib-bin = %{version}-%{release}
Provides: qatlib-devel = %{version}-%{release}
Requires: qatlib = %{version}-%{release}

%description dev
dev components for the qatlib package.


%package lib
Summary: lib components for the qatlib package.
Group: Libraries
Requires: qatlib-license = %{version}-%{release}

%description lib
lib components for the qatlib package.


%package license
Summary: license components for the qatlib package.
Group: Default

%description license
license components for the qatlib package.


%package man
Summary: man components for the qatlib package.
Group: Default

%description man
man components for the qatlib package.


%package services
Summary: services components for the qatlib package.
Group: Systemd services
Requires: systemd

%description services
services components for the qatlib package.


%prep
%setup -q -n qatlib-24.09.0
cd %{_builddir}/qatlib-24.09.0
pushd ..
cp -a qatlib-24.09.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725979310
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%autogen --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1725979310
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qatlib
cp %{_builddir}/qatlib-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/qatlib/154c1d177e5fcb47563a47d8a17b7b5548ad9072 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/qatmgr
/usr/bin/qat_init.sh
/usr/bin/qatmgr

%files dev
%defattr(-,root,root,-)
/usr/include/qat/cpa.h
/usr/include/qat/cpa_cy_common.h
/usr/include/qat/cpa_cy_dh.h
/usr/include/qat/cpa_cy_drbg.h
/usr/include/qat/cpa_cy_dsa.h
/usr/include/qat/cpa_cy_ec.h
/usr/include/qat/cpa_cy_ecdh.h
/usr/include/qat/cpa_cy_ecdsa.h
/usr/include/qat/cpa_cy_ecsm2.h
/usr/include/qat/cpa_cy_im.h
/usr/include/qat/cpa_cy_key.h
/usr/include/qat/cpa_cy_kpt.h
/usr/include/qat/cpa_cy_ln.h
/usr/include/qat/cpa_cy_nrbg.h
/usr/include/qat/cpa_cy_prime.h
/usr/include/qat/cpa_cy_rsa.h
/usr/include/qat/cpa_cy_sym.h
/usr/include/qat/cpa_cy_sym_dp.h
/usr/include/qat/cpa_dc.h
/usr/include/qat/cpa_dc_chain.h
/usr/include/qat/cpa_dc_dp.h
/usr/include/qat/cpa_dev.h
/usr/include/qat/cpa_types.h
/usr/include/qat/icp_sal.h
/usr/include/qat/icp_sal_congestion_mgmt.h
/usr/include/qat/icp_sal_poll.h
/usr/include/qat/icp_sal_user.h
/usr/include/qat/icp_sal_versions.h
/usr/include/qat/qae_mem.h
/usr/lib64/libqat.so
/usr/lib64/libusdm.so
/usr/lib64/pkgconfig/libqat.pc
/usr/lib64/pkgconfig/libusdm.pc
/usr/lib64/pkgconfig/qatlib.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libqat.so.4.3.0
/V3/usr/lib64/libusdm.so.0.1.1
/usr/lib64/libqat.so.4
/usr/lib64/libqat.so.4.3.0
/usr/lib64/libusdm.so.0
/usr/lib64/libusdm.so.0.1.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qatlib/154c1d177e5fcb47563a47d8a17b7b5548ad9072

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/qat_init.sh.8
/usr/share/man/man8/qatmgr.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/qat.service
